import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import logging

class PPTGenerator:
    def __init__(self, output_path="generated_presentation.pptx", template_path=None):
        """
        Initialize PPT Generator.
        
        Args:
            output_path: Path to save the generated presentation.
            template_path: Optional path to a PPTX template with slide masters.
        """
        self.output_path = output_path
        self.template_path = template_path
        
        # Load from template if provided, else create blank
        if template_path and os.path.exists(template_path):
            logging.info(f"Loading template from: {template_path}")
            self.prs = Presentation(template_path)
            
            # IMPORTANT: Remove any existing slides from template
            # We only want the slide masters/layouts, not content
            while len(self.prs.slides) > 0:
                rId = self.prs.slides._sldIdLst[0].rId
                self.prs.part.drop_rel(rId)
                del self.prs.slides._sldIdLst[0]
            logging.info(f"Cleared {len(self.prs.slides)} existing slides from template")
            
            self._detect_layouts()
        else:
            self.prs = Presentation()
            self.layout_map = self._default_layout_map()
    
    def _default_layout_map(self):
        """Default layout index mapping for blank presentations."""
        return {
            "title": 0,           # Title Slide
            "title_content": 1,   # Title and Content
            "section": 2,         # Section Header
            "two_content": 3,     # Two Content
            "comparison": 4,      # Comparison
            "title_only": 5,      # Title Only
            "blank": 6,           # Blank
        }
    
    def _detect_layouts(self):
        """Detect available layouts from template and create mapping."""
        self.layout_map = {}
        self.available_layouts = []
        
        for idx, layout in enumerate(self.prs.slide_layouts):
            layout_name = layout.name.lower().replace(" ", "_")
            self.layout_map[layout_name] = idx
            self.available_layouts.append({
                "index": idx,
                "name": layout.name,
                "key": layout_name
            })
        
        logging.info(f"Detected {len(self.available_layouts)} layouts from template")
        
        # Map our standard types to closest matches
        self._map_standard_layouts()
    
    def _map_standard_layouts(self):
        """Map our standard layout types to template layouts."""
        # Try to find best matches
        standard_map = {
            "title": ["title_slide", "title", "cover"],
            "title_content": ["title_and_content", "content", "bullet"],
            "two_content": ["two_content", "comparison", "two_column"],
            "section": ["section_header", "section", "divider"],
            "title_only": ["title_only", "title"],
            "blank": ["blank", "empty"]
        }
        
        for std_type, candidates in standard_map.items():
            if std_type not in self.layout_map:
                for candidate in candidates:
                    for key in self.layout_map:
                        if candidate in key:
                            self.layout_map[std_type] = self.layout_map[key]
                            break
                    if std_type in self.layout_map:
                        break
    
    def get_layout(self, layout_type):
        """Get slide layout by type name."""
        idx = self.layout_map.get(layout_type, self.layout_map.get("title_content", 1))
        return self.prs.slide_layouts[idx]

    def generate(self, session_data, include_title_slide=True):
        """
        Generates a PowerPoint presentation from session data.
        
        Args:
            session_data (dict): The session data containing outline and content.
            include_title_slide (bool): Whether to generate the cover slide.
            
        Returns:
            str: Path to the generated PPTX file.
        """
        # Title Slide
        if include_title_slide:
            title_slide_layout = self.prs.slide_layouts[0]
            slide = self.prs.slides.add_slide(title_slide_layout)
            title = slide.shapes.title
            subtitle = slide.placeholders[1]

            title.text = session_data.get("name", "AutoDeck Presentation")
            subtitle.text = "Generated by AutoDeck"

        # Content Slides
        outline = session_data.get("outline", [])
        content_map = session_data.get("content", {})
        
        # Sort keys to ensure order if numeric strings, but outline list order is safer
        # We iterate by outline to preserve order
        for index, item in enumerate(outline):
            # content keys are strings
            content_item = content_map.get(str(index))
            self._create_slide(index, item, content_item)

        try:
            self.prs.save(self.output_path)
            logging.info(f"Presentation saved to {self.output_path}")
            return self.output_path
        except Exception as e:
            logging.error(f"Failed to save presentation: {e}")
            raise

    def _create_slide(self, index, outline_item, content_item):
        """Creates a single slide."""
        
        # AUTO-FIT: Apply deterministic text fitting BEFORE rendering
        # This prevents overflow without needing LLM review
        if content_item and content_item.get("bullet_points"):
            from autodeck_core.text_fitter import auto_fit_slide
            content_item = auto_fit_slide(content_item)
        
        # Check for forced layout from design agent
        layout_type = "title_content"  # default
        if content_item and content_item.get("forced_layout"):
            layout_type = content_item["forced_layout"]
        
        # Use detected layout from template (or fallback to default)
        bullet_slide_layout = self.get_layout(layout_type)
        slide = self.prs.slides.add_slide(bullet_slide_layout)

        # Title
        title_shape = slide.shapes.title
        if content_item and "title" in content_item:
            title_shape.text = content_item["title"]
        else:
            title_shape.text = outline_item.get("title", f"Slide {index + 1}")

        # Body / Bullet Points
        body_shape = slide.placeholders[1]
        
        # Check for image
        has_image = False
        image_path = None
        if content_item and "image_suggestion" in content_item:
            img_p = content_item["image_suggestion"]
            if img_p and os.path.exists(img_p):
                has_image = True
                image_path = img_p

        # Determine Layout using Formatting Agent
        # If content hasn't been generated, use Draft layout
        is_draft = False
        if not content_item or "bullet_points" not in content_item or not content_item["bullet_points"]:
             is_draft = True
        
        # Skip FormattingAgent - it uses local Gemma which is slow
        # The template placeholder with standard_list layout works best
        layout_data = {
            "layout_type": "standard_list", 
            "content_mapping": {"main_bullets": content_item.get("bullet_points", []) if content_item else []}
        }
        
        # --- RENDERER SWITCH ---
        # IMPORTANT: forced_layout from design agent takes priority
        if content_item and content_item.get("forced_layout"):
            layout_type = content_item["forced_layout"]
            logging.info(f"Using FORCED layout: {layout_type}")
        else:
            layout_type = layout_data.get("layout_type", "standard_list")
            logging.info(f"Using default layout: {layout_type}")


        
        if is_draft:
             # Draft Layout
             body_shape = slide.placeholders[1]
             body_shape.left = Inches(1.0)
             body_shape.top = Inches(2.0)
             body_shape.width = Inches(8.0)
             body_shape.height = Inches(4.5)
             
             tf = body_shape.text_frame
             tf.word_wrap = True
             
             p = tf.add_paragraph()
             p.text = "[Draft] Content to be generated."
             p.level = 0
             if p.runs:
                 p.runs[0].font.bold = True
                 if not self.template_path:
                     p.runs[0].font.name = "Aptos"
                     p.runs[0].font.size = Pt(20)
                     p.runs[0].font.color.rgb = RGBColor(200, 0, 0)
             
             instructions = outline_item.get("description", "")
             p2 = tf.add_paragraph()
             p2.space_before = Pt(20)
             run = p2.add_run()
             run.text = f"Instructions: {instructions}"
             run.font.italic = True
             if not self.template_path:
                 run.font.name = "Aptos"
                 run.font.size = Pt(14)
                 run.font.color.rgb = RGBColor(80, 80, 80)
             
             # Notes
             notes_slide = slide.notes_slide
             text_frame = notes_slide.notes_text_frame
             text_frame.text = f"Goal: {instructions}"
             return

        # Visual Overrides
        overrides = content_item.get("visual_overrides", {}) if content_item else {}
        base_font_size = overrides.get("font_size", 18)
        line_spacing = overrides.get("line_spacing", 1.15)
        para_spacing = overrides.get("para_spacing", 12)  # points
        text_padding = overrides.get("text_padding", 0.1)  # inches
        text_align = overrides.get("text_align", "left")
        
        # Map text_align string to enum
        from pptx.enum.text import PP_ALIGN
        align_map = {
            "left": PP_ALIGN.LEFT,
            "center": PP_ALIGN.CENTER,
            "right": PP_ALIGN.RIGHT,
            "justify": PP_ALIGN.JUSTIFY
        }
        alignment = align_map.get(text_align, PP_ALIGN.LEFT)

        # Helper for adding bullet lists with all formatting
        def add_bullet_list(left, top, width, height, points, font_size=base_font_size):
            txBox = slide.shapes.add_textbox(left, top, width, height)
            tf = txBox.text_frame
            tf.word_wrap = True
            
            # Apply text padding (inner margins)
            tf.margin_left = Inches(text_padding)
            tf.margin_right = Inches(text_padding)
            tf.margin_top = Inches(text_padding / 2)
            tf.margin_bottom = Inches(text_padding / 2)
            
            for point in points:
                p = tf.add_paragraph()
                p.level = 0
                p.space_before = Pt(para_spacing)
                p.space_after = Pt(para_spacing / 2)
                p.line_spacing = line_spacing
                p.alignment = alignment
                
                # Basic formatting
                clean_text = point.strip()
                if clean_text.startswith("- ") or clean_text.startswith("* "):
                    clean_text = clean_text[2:]
                
                # Markdown bold support
                parts = clean_text.split("**")
                for i, part in enumerate(parts):
                    if not part: continue
                    run = p.add_run()
                    run.text = part
                    font = run.font
                    
                    # Only set font properties if NOT using a template
                    # Template slides inherit from slide master
                    if not self.template_path:
                        font.name = "Aptos"
                        font.size = Pt(font_size)
                        font.color.rgb = RGBColor(0, 0, 0)
                    else:
                        # Only set size from overrides if specified
                        if font_size != 18:  # Non-default size
                            font.size = Pt(font_size)
                    
                    if i % 2 == 1:
                        font.bold = True


        mapping = layout_data.get("content_mapping", {})

        if layout_type == "two_column":
            # Left Col
            add_bullet_list(Inches(0.5), Inches(2.0), Inches(4.2), Inches(5.0), mapping.get("left_points", []))
            # Right Col
            add_bullet_list(Inches(5.3), Inches(2.0), Inches(4.2), Inches(5.0), mapping.get("right_points", []))
            
            # Optional Titles for columns could be added here if mapping has "left_title"

        elif layout_type == "grid_2x2":
            # Top Left
            add_bullet_list(Inches(0.5), Inches(1.8), Inches(4.2), Inches(2.5), mapping.get("top_left", []))
            # Top Right
            add_bullet_list(Inches(5.3), Inches(1.8), Inches(4.2), Inches(2.5), mapping.get("top_right", []))
            # Bottom Left
            add_bullet_list(Inches(0.5), Inches(4.5), Inches(4.2), Inches(2.5), mapping.get("bottom_left", []))
            # Bottom Right
            add_bullet_list(Inches(5.3), Inches(4.5), Inches(4.2), Inches(2.5), mapping.get("bottom_right", []))
            
        elif layout_type == "big_stat":
            # Big Centered Text
            txBox = slide.shapes.add_textbox(Inches(1.0), Inches(2.5), Inches(8.0), Inches(2.0))
            tf = txBox.text_frame
            tf.word_wrap = True
            p = tf.add_paragraph()
            p.text = str(mapping.get("stat", "")) 
            p.alignment = PP_ALIGN.CENTER
            if p.runs:
                 p.runs[0].font.bold = True
                 p.runs[0].font.size = Pt(60)  # HUGE
                 if not self.template_path:
                     p.runs[0].font.name = "Aptos"
                     p.runs[0].font.color.rgb = RGBColor(0, 0, 0)
            
            p2 = tf.add_paragraph()
            p2.text = str(mapping.get("description", ""))
            p2.alignment = PP_ALIGN.CENTER
            if p2.runs:
                 p2.runs[0].font.size = Pt(24)
                 if not self.template_path:
                     p2.runs[0].font.name = "Aptos"
                     p2.runs[0].font.color.rgb = RGBColor(80, 80, 80)
                 
        elif layout_type == "image_text_split" and has_image:
             # Image Left, Text Right (or vice versa, sticking to standardized layout for now)
             # Let's put Text Left, Image Right as it's cleaner for bullet reading
             
             # Text Box Left
             add_bullet_list(Inches(0.5), Inches(2.0), Inches(4.5), Inches(5.0), mapping.get("main_bullets", []))
             
             # Image Right
             try:
                 left = Inches(5.2)
                 top = Inches(2.0)
                 height = Inches(4.5)
                 slide.shapes.add_picture(image_path, left, top, height=height)
             except Exception as e:
                 logging.error(f"Failed to add image {image_path}: {e}")

        else:
            # Standard List - USE THE TEMPLATE'S BODY PLACEHOLDER
            # This ensures proper positioning and sizing from the template design
            
            bullets = mapping.get("main_bullets", [])
            if not bullets:
                bullets = content_item.get("bullet_points", []) if content_item else []
            
            print(f"Using TEMPLATE PLACEHOLDER for standard_list")
            print(f"Placeholder size: left={body_shape.left}, width={body_shape.width}")
            
            # Use the placeholder's text frame directly
            tf = body_shape.text_frame
            tf.word_wrap = True
            tf.clear()  # Clear any default placeholder text
            
            # Apply text formatting from overrides
            for i, point in enumerate(bullets):
                p = tf.add_paragraph()
                p.level = 0
                p.space_before = Pt(para_spacing)
                p.space_after = Pt(para_spacing / 2)
                p.line_spacing = line_spacing
                p.alignment = alignment
                
                # Clean up bullet point text
                clean_text = point.strip()
                if clean_text.startswith("- ") or clean_text.startswith("* "):
                    clean_text = clean_text[2:]
                
                # Markdown bold support
                parts = clean_text.split("**")
                for j, part in enumerate(parts):
                    run = p.add_run()
                    run.text = part
                    font = run.font
                    
                    if not self.template_path:
                        font.name = "Aptos"
                        font.size = Pt(base_font_size)
                        font.color.rgb = RGBColor(0, 0, 0)
                    else:
                        if base_font_size != 18:
                            font.size = Pt(base_font_size)
                    
                    # Every odd part (1, 3, 5...) was between ** markers = bold
                    if j % 2 == 1:
                        font.bold = True
            
            print(f"Added {len(bullets)} bullets to template placeholder")





            
        # Speaker Notes
        if content_item and "speaker_notes" in content_item:
            notes_slide = slide.notes_slide
            text_frame = notes_slide.notes_text_frame
            text_frame.text = content_item["speaker_notes"]
